name: JwtCI

on:
  push:
    paths: [ jwt/** ]
  pull_request:
    paths: [ jwt/** ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kotlin
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          run: ./gradlew :jwt:test